% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Tugas Kuliah Analisis Regresi Pertemuan 7},
  pdfauthor={Nafisa Zalfa Maulida - G1401221092},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Tugas Kuliah Analisis Regresi Pertemuan 7}
\author{Nafisa Zalfa Maulida - G1401221092}
\date{2024-03-06}

\begin{document}
\maketitle

\#\#Data

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'readxl' was built under R version 4.3.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OtherTok{\textless{}{-}}\FunctionTok{read\_excel}\NormalTok{(}\StringTok{"D:/SEMESTER 4/Analisis Regresi/Pertemuan 7/Data Anreg Kuliah Pertemuan 7.xlsx"}\NormalTok{)}
\NormalTok{data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 3
##      No.     X     Y
##    <dbl> <dbl> <dbl>
##  1     1     2    54
##  2     2     5    50
##  3     3     7    45
##  4     4    10    37
##  5     5    14    35
##  6     6    19    25
##  7     7    26    20
##  8     8    31    16
##  9     9    34    18
## 10    10    38    13
## 11    11    45     8
## 12    12    52    11
## 13    13    53     8
## 14    14    60     4
## 15    15    65     6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'forcats' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'lubridate' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.4
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.4.4     v tibble    3.2.1
## v lubridate 1.9.3     v tidyr     1.3.0
## v purrr     1.0.2     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggridges)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'ggridges' was built under R version 4.3.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(GGally)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'GGally' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## Registered S3 method overwritten by 'GGally':
##   method from   
##   +.gg   ggplot2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(plotly)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'plotly' was built under R version 4.3.2
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'plotly'
## 
## The following object is masked from 'package:ggplot2':
## 
##     last_plot
## 
## The following object is masked from 'package:stats':
## 
##     filter
## 
## The following object is masked from 'package:graphics':
## 
##     layout
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(lmtest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'lmtest' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## Loading required package: zoo
\end{verbatim}

\begin{verbatim}
## Warning: package 'zoo' was built under R version 4.3.3
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'zoo'
## 
## The following objects are masked from 'package:base':
## 
##     as.Date, as.Date.numeric
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(stats)}
\end{Highlighting}
\end{Shaded}

\#\#Model Regresi Awal

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(model\_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.1628 -4.7313 -0.9253  3.7386  9.0446 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 46.46041    2.76218   16.82 3.33e-10 ***
## X           -0.75251    0.07502  -10.03 1.74e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.891 on 13 degrees of freedom
## Multiple R-squared:  0.8856, Adjusted R-squared:  0.8768 
## F-statistic: 100.6 on 1 and 13 DF,  p-value: 1.736e-07
\end{verbatim}

Model Regresi: \[\hat Y = 46.46041 - 0.75251X +e\] Karena belum melalui
serangkaian uji asumsi, maka diperlukan eksplorasi kondisi, pengujian
asumsi Gauss-Markov, dan normalitas untuk menghasilkan model terbaik.

\#\#Eksplorasi Data \#Plot Hubungan X dan Y

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{X, }\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-4-1.pdf}

Berdasarkan scatter plot di atas, dapat diketahui bahwa X dan Y tidak
mempunyai hubungan linear karena cenderung membentuk pola parabola.

\#\#Plot Sisaan vs Urutan

\begin{Shaded}
\begin{Highlighting}[]
 \FunctionTok{plot}\NormalTok{(}\AttributeTok{x =} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(data)[}\DecValTok{1}\NormalTok{],}
 \AttributeTok{y =}\NormalTok{ model\_lm}\SpecialCharTok{$}\NormalTok{residuals,}
 \AttributeTok{type =} \StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{,}
 \AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{,}
 \AttributeTok{xlab =} \StringTok{"Observation"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-5-1.pdf}
Sebaran tersebut membentuk pola kurva menandakan sisaan tidak saling
bebas.

\#\#Uji Normalitas

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Y)}
\FunctionTok{qqline}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Y, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{shapiro.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  data$Y
## W = 0.89636, p-value = 0.08374
\end{verbatim}

QQ Plot cenderung menunjukkan bahwa data yang digunakan menyebar normal.
Hal tersebut juga didukung dengan hasil Shapiro Test yang besarnya lebih
dari 0.05, yaitu 0.89636.

\#\#Uji Autokorelasi

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{acf}\NormalTok{(model\_lm}\SpecialCharTok{$}\NormalTok{residuals)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dwtest}\NormalTok{(model\_lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Durbin-Watson test
## 
## data:  model_lm
## DW = 0.48462, p-value = 1.333e-05
## alternative hypothesis: true autocorrelation is greater than 0
\end{verbatim}

Nilai autokorelasi pada lag 1 dan lag 2 berada di luar batas kepercayaan
95\%, yaitu pada lag 1 = 0,5 dan pada lag 2 = 0.4. Hal tersebut
menunjukkan bahwa autokorelasi pada lag 1 dan 2 adalah signifikan.

Oleh karena itu, asumsi Gauss-Markov tidak terpenuhi (asumsi
non-autokorelasi). Hal tersebut pun diperkuat dengan p-test pada uji
Durbin-Watson bernilai kurang dari 0.05.

\#\#Uji Homoskedastisitas

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model\_lm, }\AttributeTok{which =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-9-1.pdf}

Grafik tersebut menunjukkan bahwa varians residual konstan. Varian
residual cenderung meningkat seiring dengan nilai prediksi. Hal tersebut
akan mengindikasi bahwa homoskedastisitas terjadi.

\#\#Transformasi

\#\#WLS

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resid\_abs }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(model\_lm}\SpecialCharTok{$}\NormalTok{residuals)}
\NormalTok{fitted\_val }\OtherTok{\textless{}{-}}\NormalTok{ model\_lm}\SpecialCharTok{$}\NormalTok{fitted.values}
\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(resid\_abs }\SpecialCharTok{\textasciitilde{}}\NormalTok{ fitted\_val, data)}
\NormalTok{data.weights }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{fitted.values}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{data.weights}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          1          2          3          4          5          6          7 
## 0.03414849 0.03489798 0.03541143 0.03620311 0.03730067 0.03874425 0.04091034 
##          8          9         10         11         12         13         14 
## 0.04257072 0.04361593 0.04507050 0.04779711 0.05077885 0.05122749 0.05454132 
##         15 
## 0.05710924
\end{verbatim}

\#\#Hasil model regresi yang terboboti:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_weighted }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Y}\SpecialCharTok{\textasciitilde{}}\NormalTok{X, }\AttributeTok{data =}\NormalTok{ data, }\AttributeTok{weights =}\NormalTok{ data.weights)}
\FunctionTok{plot}\NormalTok{(model\_weighted)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-11-1.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-11-2.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-11-3.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-11-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model\_weighted)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = Y ~ X, data = data, weights = data.weights)
## 
## Weighted Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.46776 -1.09054 -0.06587  0.77203  1.85309 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 45.41058    2.90674  15.623 8.35e-10 ***
## X           -0.71925    0.07313  -9.835 2.18e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.204 on 13 degrees of freedom
## Multiple R-squared:  0.8815, Adjusted R-squared:  0.8724 
## F-statistic: 96.73 on 1 and 13 DF,  p-value: 2.182e-07
\end{verbatim}

Berdasarkan hasil transformasi WLS, dapat diketahui bahwa WLS belum
cukup efektif untuk mentransformasi model regresi. Hal itu dapat
dibuktikan dari hasil eksplorasi yang masih belum memenuhi asumsi
Gauss-Markov.

\#\#Transformasi Akar: pada x,y atau X dan Y

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{y =} \FunctionTok{sqrt}\NormalTok{(Y)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{x =} \FunctionTok{sqrt}\NormalTok{(X))}

\NormalTok{model\_sqrtx }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X, }\AttributeTok{data =}\NormalTok{ newdata)}
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{X, }\AttributeTok{y =}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model\_sqrtx)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-14-1.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-14-2.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-14-3.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-14-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model\_sqrtx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ X, data = newdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.53998 -0.38316 -0.01727  0.36045  0.70199 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  7.015455   0.201677   34.79 3.24e-14 ***
## X           -0.081045   0.005477  -14.80 1.63e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4301 on 13 degrees of freedom
## Multiple R-squared:  0.9439, Adjusted R-squared:  0.9396 
## F-statistic: 218.9 on 1 and 13 DF,  p-value: 1.634e-09
\end{verbatim}

\#\#Uji Autokorelasi Model Regresi Transformasi

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dwtest}\NormalTok{(model\_sqrtx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Durbin-Watson test
## 
## data:  model_sqrtx
## DW = 1.2206, p-value = 0.02493
## alternative hypothesis: true autocorrelation is greater than 0
\end{verbatim}

Nilai DW yang rendah dan p-value yang signifikan menunjukkan ada
autokorelasi positif pada Durbin Watson. Selain itu, dibuktikan dengan
p-value yang bernilai kurang dari 0.05.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_sqrt }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x, }\AttributeTok{data =}\NormalTok{ newdata)}
\FunctionTok{plot}\NormalTok{(}\AttributeTok{x =}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{x, }\AttributeTok{y =}\NormalTok{ newdata}\SpecialCharTok{$}\NormalTok{y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(model\_sqrt)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-18-1.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-18-2.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-18-3.pdf}
\includegraphics{Tugas-Kuliah-Analisis-Regresi-Pertemuan-7---Nafisa-Zalfa-Maulida_files/figure-latex/unnamed-chunk-18-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(model\_sqrt)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x, data = newdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.42765 -0.17534 -0.05753  0.21223  0.46960 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  8.71245    0.19101   45.61 9.83e-16 ***
## x           -0.81339    0.03445  -23.61 4.64e-12 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.2743 on 13 degrees of freedom
## Multiple R-squared:  0.9772, Adjusted R-squared:  0.9755 
## F-statistic: 557.3 on 1 and 13 DF,  p-value: 4.643e-12
\end{verbatim}

\#\#Uji Autokorelasi Model Regresi

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dwtest}\NormalTok{(model\_sqrt)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Durbin-Watson test
## 
## data:  model_sqrt
## DW = 2.6803, p-value = 0.8629
## alternative hypothesis: true autocorrelation is greater than 0
\end{verbatim}

P-value lebih besar dari 0.05, yaitu 0.8629 menunjukkan bahwa tidak ada
cukup bukti untuk menolak H0. Dimana H0 adalah tidak ada autokorelasi.

Dari hasil transformasi, dapat disimpulkan jika transformasi akar Y
membuat persamaan regresi jadi lebih efektif dengan model regresi
menjadi: \[Y^* = 8.71245 - 0.81339X^* + e\] \[Y^* = \sqrt Y\]
\[X^* = \sqrt X\] \#Dilakukan Transformasi Balik Menjadi:
\[\hat Y=(8.71245-0.81339X^\frac12)^2 + e\] \#Interpretasi Model
tersebut mengindikasi bahwa adanya hubungan berbanding terbalik (kuadrat
negatif) antara Y dengan X. Saat X meningkat, Y akan cenderung turun
dengan kecepatan yang semakin cepat. Nilai konstanta 8.71245 mewakili
nilai Y ketika X=0. Koefisien regresi untuk variabel X adalah -0.81339.
Semakin besar nilai absolut koefisien, semakin besar pengaruh X terhadap
Y.

\end{document}
